---
title: "Random Forest - Lab Exercise 10"
author: "19BPS1028_Sparsh Raj"
date: "23/04/2022"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())
library('stats19')
library('dplyr')
library('randomForest')
```

#### Read the dataset.We have taken the iris dataset. 
```{r}
mydata=iris
head(mydata)
summary(mydata)
```

#### Split into Training and Testing data
```{r}
index=sample(2,nrow(mydata), replace=TRUE,prob=c(0.7,0.3))
training=mydata[index==1,]
testing=mydata[index==2,]
```

#### Random Forest Implementation
```{r}
RFM <- randomForest(Species ~ .,data=training, importance=T, proximity=T)
Species_Pred=predict(RFM,testing)
testing$Species_Pred=Species_Pred
head(testing)

```


```{r}
CFM=table(testing$Species,testing$Species_Pred)
CFM
```

### Car Dataset

```{r}
data1 <- read.csv("cars.csv", header = TRUE)
head(data1)
str(data1)
summary(data1)
```


```{r}
data1$fueltype<-as.factor(data1$fueltype)  # convert numeric to factor
str(data1)
```


#### Split into Training and Testing data
```{r}
index_1=sample(2,nrow(data1), replace=TRUE,prob=c(0.7,0.3))
train=data1[index_1==1,]
test=data1[index_1==2,]
```

#### Random Forest Implementation
```{r}
RFM1<- randomForest(fueltype~ .,data=train, importance=T, proximity=T)
fueltype_Pred1=predict(RFM1,test)
test$fueltype_Pred1=fueltype_Pred1
head(test)

```


```{r}
CFM_1=table(test$fueltype,test$fueltype_Pred1)
CFM_1
```
